config/routes.rb
Nihoncha::Application.routes.draw do

  resources :cashes

  root :to => 'welcome#index'

  devise_for :users
  get 'root', :to => 'wishes#index', :as => :user_root

  resources :wishes, :except => [:new, :edit, :update] do
    post :preview, :on => :collection
  end

end

app/models/cash.rb
class Cash < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :paypal, :zip, :pref, :address, :birthday, :sex,
                  :public_flag
  has_many :wishes
  has_many :cashes
end

app/models/wish.rb
# -*- coding: utf-8 -*-
class Wish < ActiveRecord::Base
  belongs_to :user

  def fetch
    html = nil
    doc = Nokogiri::HTML(open(URI.encode(uri)).read)
    if title = doc.xpath('//title').first
      self.name = title.text.split(/\s*[:：]\s*/)[1]
    end
    if price = (doc.xpath("//b[@class='priceLarge']").first || doc.xpath("//span[@class='price']").first)
      self.price = price.text.slice(/[\d,]+/).delete(',').to_i
    end
    if description = doc.xpath("//div[@class='productDescriptionWrapper']").first
      self.description = description.text
    end
    if prod_image = doc.xpath("//img[@id='prodImage']").first
      self.image_url = prod_image['src']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter{ @javascripts = [] }
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  before_filter :authenticate_user!
  # GET /cashes
  # GET /cashes.xml
  def index
    @cashes = current_user.cashes.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cashes }
    end
  end

  # GET /cashes/1
  # GET /cashes/1.xml
  def show
    @cash = current_user.cashes.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cash }
    end
  end

  # GET /cashes/new
  # GET /cashes/new.xml
  def new
    @cash = current_user.cashes.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cash }
    end
  end

  # GET /cashes/1/edit
  def edit
    @cash = current_user.cashes.find(params[:id])
  end

  # POST /cashes
  # POST /cashes.xml
  def create
    @cash = current_user.cashes.new(params[:cash])
    @cash.user_id = current_user.id if user_signed_in?

    respond_to do |format|
      if @cash.save
        format.html { redirect_to(@cash, :notice => 'Cash was successfully created.') }
        format.xml  { render :xml => @cash, :status => :created, :location => @cash }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cash.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cashes/1
  # PUT /cashes/1.xml
  def update
    @cash = current_user.cashes.find(params[:id])

    respond_to do |format|
      if @cash.update_attributes(params[:cash])
        format.html { redirect_to(@cash, :notice => 'Cash was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cash.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cashes/1
  # DELETE /cashes/1.xml
  def destroy
    @cash = current_user.cashes.find(params[:id])
    @cash.destroy

    respond_to do |format|
      format.html { redirect_to(cashes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to :user_root
      return
    end
  end

end

app/controllers/wishes_controller.rb
# -*- coding: utf-8 -*-
class WishesController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!
  def index
    @wishes = current_user.wishes.order('created_at DESC').all
    @wish = current_user.wishes.new
    respond_to do |format|
      format.html
      format.xml  { render :xml => @wishes }
    end
  end

  def show
    @wish = current_user.wishes.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @wish }
    end
  end

  def create
    @wish = current_user.wishes.new(params[:wish])
    if @wish.save
      flash[:notice] = '登録しました'
    else
      flash[:alert] = '登録に失敗しました'
    end
    respond_with(@wish)
  end

  def destroy
    @wish = current_user.wishes.find(params[:id])
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to(wishes_url) }
      format.xml  { head :ok }
    end
  end

  def preview
    @wish = current_user.wishes.new(params[:wish])
    @wish.fetch
    respond_with(@wish)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/cashes/_form.html.erb
<%= form_for(@cash) do |f| %>
  <% if @cash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cash.errors.count, "error") %> prohibited this cash from being saved:</h2>

      <ul>
      <% @cash.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"用途" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :"金額" %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cashes/edit.html.erb
<div id="wide">
  <h2>用途の変更</h2>
  <p>
    <%= render 'form' %>
  </p>
  <%= link_to '表示', @cash %> |
  <%= link_to '戻る', cashes_path %>
</div><!-- wide end -->

app/views/cashes/index.html.erb
<div id="wide">
	<h2><%= user_signed_in? ? current_user.email : '○○' %>のおこづかい帳</h2>

  <table>
    <tr>
      <th>日付</th>
      <th>用途</th>
      <th>金額</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @cashes.each do |cash| %>
    <tr>
      <td><%= cash.created_at.in_time_zone('Osaka').strftime("%Y/%m/%d")%></td>
      <td><%= cash.name %></td>
      <td align="right">￥<%= cash.price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse %></td>
      <td><%= link_to '[変更]', edit_cash_path(cash) %></td>
      <td><%= link_to '[削除]', cash, :confirm => '削除していいですか？', :method => :delete %></td>
    </tr>
    <% end %>
  </table>
  <p>
    <%= link_to '新規作成', new_cash_path %>
  </p>
  <div id="totop"><a href="#">ページのトップへ戻る</a></div><!-- toptop end -->
  <p>
    <%= link_to 'トップページへ戻る', root_path %>
  </p>  
</div><!-- wide end -->

app/views/cashes/new.html.erb
<div id="wide">
  <h2>新たな用途</h2>
  <p>
    <%= render 'form' %>
  </p>
</div><!-- wide end -->

app/views/cashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>名前:</b>
  <%= @cash.name %>
</p>

<p>
  <b>金額:</b>
  <%= @cash.price %>
</p>


<%= link_to '編集', edit_cash_path(@cash) %> |
<%= link_to '戻る', cashes_path %>

app/views/layouts/_notice.html.erb
<% if flash[:notice] -%>
   <div class="notice"><%= flash[:notice] %></div>
<% end -%>
<% if flash[:alert] -%>
   <div class="alert"><%= flash[:alert] %></div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  xml:lang="ja" lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>minami.rb nihonchaプロジェクト</title>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
<link href="stylesheets/base.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="wrapper">
  <div id="temp">
    <%= render 'shared/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </div><!-- temp end -->
</div><!-- wrapper end -->
<% @javascripts.each do |js| -%>
  <%= javascript_include_tag js %>
<% end -%>
</body>
</html>

app/views/root/index.html.erb
<h2>ほーむ</h2>
<p>次にXXX円浪費すると次はXXXをプレゼンとします☆</p>

app/views/shared/_footer.html.erb
    <div id="footer">
      <address>Copyright &copy; 2010 minamirb.nihoncha All Rights Reserved.</address>
    </div><!-- footer end -->

app/views/shared/_header.html.erb
    <div id="header">
      <h1><%= link_to 'nihonchaプロジェクト', root_path  %></h1>
    </div><!-- header end -->
    <% if current_user %>
    <div id="menu">
      <ul>
        <li><%= link_to '欲しいもの', wishes_path %></li>
        <li><%= link_to 'おこづかい帳', cashes_path %></li>
        <!-- 
          <li><a href="sample.html">MENU3</a></li>
          <li><a href="sample.html">MENU4</a></li>
        -->
      </ul>
    </div><!-- menu end -->
    <% end %>
    <div id="navi">
      <ul>
        <li><%= link_to 'ログアウト',  destroy_user_session_path, :class => 'signOut' if current_user %></li>
        <!-- <li><a href="#">navi2</a></li> -->
      </ul>
    </div><!-- navi end -->

app/views/welcome/index.html.erb
<div id="wide">
  <h2>minami.rb nihonchaプロジェクト</h2>
  <p><%= link_to 'ログイン', [ :new, :user_session ] %></p>
  <p><%= link_to 'ユーザ登録', [ :new, :user_registration ] %></p>
  <p><%= link_to 'パスワード再発行', [ :new, :user_registration ] %></p>
  <p><%= link_to '登録確認メール再送信', [ :new, :user_confirmation ] %></p>
</div>

app/views/wishes/index.html.erb
<% @javascripts += ['jquery.lightboxLib', 'wishes/index'] %>
<div id="wide">
  <h2>欲しいものリスト</h2>
  
  <%= form_for(@wish, :url => preview_wishes_path) do |f| %>
    URL:&nbsp;<%= f.text_field :uri, :size => 59 %><%= f.submit 'プレビュー' %><%= image_tag('ajax-loader.gif', :style => 'display: none;', :id => 'ajax_loader') %>
  <% end %>
  <% @wishes.each do |wish| %>
    <h3><%= link_to wish.name, wish%>&nbsp;&nbsp;<span>&yen;<%=  wish.price %><span></h3>
    <p>
      <%= image_tag wish.image_url, :style => 'float: left;' if wish.image_url %>
      <%= wish.description %>
      <div style="clear:both;"></div>
    </p>
    <p style="text-align: right;"><%= link_to '[削除]', wish, :confirm => '削除してもよろしいですか?', :method => :delete %></p>
  <% end %>
  <p>
    <%= link_to 'トップページへ戻る', root_path %>
  </p>
  <div id="totop"><a href="#">ページのトップへ戻る</a></div><!-- toptop end -->
</div><!-- wide end -->

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uri:</b>
  <%= @wish.uri %>
</p>

<p>
  <b>Name:</b>
  <%= @wish.name %>
</p>

<p>
  <b>Price:</b>
  <%= @wish.price %>
</p>

<p>
  <b>Image url:</b>
  <%= @wish.image_url %>
</p>

<p>
  <b>Thumbneil url:</b>
  <%= @wish.thumbneil_url %>
</p>

<p>
  <b>Bought:</b>
  <%= @wish.bought %>
</p>

<p>
  <b>User:</b>
  <%= @wish.user %>
</p>


<%= link_to '戻る', wishes_path %>